"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .streamedtoolassistedchattoken import (
    StreamedToolAssistedChatToken,
    StreamedToolAssistedChatTokenTypedDict,
)
from .streamedtoolassistedchattoolstatus import (
    StreamedToolAssistedChatToolStatus,
    StreamedToolAssistedChatToolStatusTypedDict,
)
from friendli.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated


StreamedToolAssistedChatResultTypedDict = Union[
    StreamedToolAssistedChatTokenTypedDict, StreamedToolAssistedChatToolStatusTypedDict
]
r"""A server-sent event containing chat completions content."""


StreamedToolAssistedChatResult = Annotated[
    Union[
        Annotated[StreamedToolAssistedChatToken, Tag("ping")],
        Annotated[StreamedToolAssistedChatToolStatus, Tag("completion")],
    ],
    Discriminator(lambda m: get_discriminator(m, "event", "event")),
]
r"""A server-sent event containing chat completions content."""
