# coding: utf-8

"""
    Barion API

    Integrate with ease and get unbeatable fees and data that helps you grow your business.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BalanceChangeType(str, Enum):
    """
    BalanceChangeType
    """

    """
    allowed enum values
    """
    NOCHANGE = 'NoChange'
    CREDIT = 'Credit'
    DEBIT = 'Debit'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BalanceChangeType from a JSON string"""
        return cls(json.loads(json_str))


