# Generated by Django 5.1.3 on 2024-11-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField(db_index=True)),
                ('value', models.BinaryField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ttl_seconds', models.BigIntegerField(db_index=True, default=0)),
            ],
        ),
    ]
