python hello.py
python example_frontier.py
python example_parallel.py
python example_replication.py
python example_replication_with_confidence.py
python example_simple.py
python example_solver.py
python oqo_example_all_variables.py
python oqo_example_cell_tower_location.py
python oqo_example_cell_tower_polygon_location.py
python oqo_example_constraint.py
python oqo_example_constraint_evaluator.py
python oqo_example_frontier.py
python oqo_example_gfo_convex.py
python oqo_example_gfo_non_convex.py
python oqo_example_objective_evaluator.py
python oqo_example_parabola.py
python oqo_example_parallel_evaluations.py
python oqo_example_permutation.py
python oqo_example_radio_antenna.py
python oqo_example_replications.py
python oqo_example_replications_with_confidence.py
python oqo_example_simulation.py
python oqo_example_status_monitor.py
python oqo_example_suggested_runs.py
python oqo_example_user_stop.py
