DEFAULT_CONNECTION_TIMEOUT = 60  # In seconds
MIN_SERVER_VERSION = '24.4.0'
DEFAULT_PAGE_SIZE = 50
JOB_POLL_INTERVAL = 3
JOB_WAIT_TIMEOUT = 1800
STREAM_EVENT_LIMIT = 1000
DEFAULT_NUM_CLUSTERS = 5
DEFAULT_NUM_TAGS = 5
