# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class PyHexmoveImuData:
    x_angle: float
    y_angle: float
    z_angle: float
    x_velocity: float
    y_velocity: float
    z_velocity: float
    x_angle_offset: float
    y_angle_offset: float
    z_angle_offset: float

class PyHexmoveImuReader:
    def __new__(cls,interface:str, serial_number:int, model:int): ...
    def get_data(self) -> PyHexmoveImuData:
        ...

    def get_angles(self) -> tuple[float, float, float]:
        ...

    def get_velocities(self) -> tuple[float, float, float]:
        ...

    def zero_imu(self, duration_ms = ...,max_retries = ...,max_variance = ...) -> None:
        ...

    def stop(self) -> None:
        ...


