DEFAULT_IGNORE_PATTERNS = {
    # Directories to ignore
    '.git',
    '__pycache__',
    '.pytest_cache',
    'node_modules',
    'coverage',
    'venv',
    '.venv',
    '.env',
    '.vscode',
    '.idea',
    'build',
    'dist',
    '.devcontainer',
    '.production',
    '.ipython',
    '.next',
    '.out',
    '.vercel',
    '.envs',
    'locale',
    'package-lock.json',
    'static',
    # File patterns to ignore
    '*.pyc',
    '*.log',
    '*.sqlite3',
    '*.db',
    'poetry.lock',
    '.gitignore',
    '.dockerignore',
    '.gitattributes',
    '.pre-commit-config.yaml',
    '.secret',
}
