
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-14T16:34:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9dcd290dc6532149fcd0b4f26fb5e9af4bf4bf36",
 "version": "0.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
