
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-06T15:27:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3afe9d00fd1a26bbc398ba1b9fea0670dde09424",
 "version": "2.49.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
