"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import finetunedmodelresponse as components_finetunedmodelresponse
from typing import Optional


@dataclasses.dataclass
class GetFineTunedModelsIDRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetFineTunedModelsIDResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    fine_tuned_model_response: Optional[components_finetunedmodelresponse.FineTunedModelResponse] = dataclasses.field(default=None)
    r"""OK"""
    

