
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-12T10:15:30+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e16ab347639b06d21ee31f0818da94cd50d1a64",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
