# Generated by Django 3.2.18 on 2024-08-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekdjselfmigration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='migrationrecord',
            options={'verbose_name': '迁移记录'},
        ),
    ]
