# Generated by Django 3.2.18 on 2024-08-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekdjselfmigration', '0002_alter_migrationrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRecordCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField(verbose_name='数据块')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('migrations', models.JSONField(verbose_name='迁移状态')),
            ],
            options={
                'verbose_name': '迁移记录纠错',
            },
        ),
        migrations.RemoveField(
            model_name='migrationrecord',
            name='mid',
        ),
    ]
