
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-11T17:06:50-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "98592bd40e9457718248345f21a5463bf9eab689",
 "version": "3.1.2.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
