# coding: utf-8

"""
    Barion API

    Integrate with ease and get unbeatable fees and data that helps you grow your business.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HistoryItemType(str, Enum):
    """
    HistoryItemType
    """

    """
    allowed enum values
    """
    INTERNALTRANSFER = 'InternalTransfer'
    INTERNALTRANSFERTOEXTERNALUSER = 'InternalTransferToExternalUser'
    ELECTRONICPAYMENT = 'ElectronicPayment'
    CARDPAYMENT = 'CardPayment'
    REFUNDTOCARD = 'RefundToCard'
    PAYEETRANSACTION = 'PayeeTransaction'
    GATEWAYFEE = 'GatewayFee'
    CARDPROCESSINGFEE = 'CardProcessingFee'
    CARDTOPUP = 'CardTopUp'
    UNSUCCESSFULTRANSFER = 'UnsuccessfulTransfer'
    WIRETOPUP = 'WireTopUp'
    CASHTOPUP = 'CashTopUp'
    WITHDRAW = 'Withdraw'
    UNSUCCESSFULWITHDRAW = 'UnsuccessfulWithdraw'
    REFUNDTOWALLET = 'RefundToWallet'
    UNSUCCESSFULREFUNDTOCARD = 'UnsuccessfulRefundToCard'
    ISSUEFROMCUSTODY = 'IssueFromCustody'
    WITHDRAWFEE = 'WithdrawFee'
    REJECTEDWITHDRAW = 'RejectedWithdraw'
    REJECTEDWITHDRAWFEE = 'RejectedWithdrawFee'
    BANKTRANSFERPAYMENT = 'BankTransferPayment'
    REFUNDTOBANKACCOUNT = 'RefundToBankAccount'
    UNSUCCESSFULREFUNDTOBANKACCOUNT = 'UnSuccessfulRefundToBankAccount'
    BANKTRANSFERPAYMENTFEE = 'BankTransferPaymentFee'
    BARIONBALANCEPROCESSINGFEE = 'BarionBalanceProcessingFee'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HistoryItemType from a JSON string"""
        return cls(json.loads(json_str))


