
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-15T17:42:59+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "efa49b0062a1ac2effdf22024d66c03acaa3a620",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
