
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-13T02:32:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "afbdac8f1acd9e3227431b4078b601d8a7ea2032",
 "version": "1.1.47"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
