# coding: utf-8

"""
    Barion API

    Integrate with ease and get unbeatable fees and data that helps you grow your business.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_barion.models.balance_change_type import BalanceChangeType

class TestBalanceChangeType(unittest.TestCase):
    """BalanceChangeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceChangeType(self):
        """Test BalanceChangeType"""
        # inst = BalanceChangeType()

if __name__ == '__main__':
    unittest.main()
