# coding: utf-8

"""
    Barion API

    Integrate with ease and get unbeatable fees and data that helps you grow your business.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_barion.models.history_item_type import HistoryItemType

class TestHistoryItemType(unittest.TestCase):
    """HistoryItemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoryItemType(self):
        """Test HistoryItemType"""
        # inst = HistoryItemType()

if __name__ == '__main__':
    unittest.main()
