"""Utility for automating backups of a specific file or directory"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['create_backup', 'clean_dates', 'run_backup']

# %% ../nbs/00_core.ipynb 3
import shutil, os, time, pprint, logging
from pathlib import Path
from fastcore.script import call_parse
from datetime import datetime, timedelta

# %% ../nbs/00_core.ipynb 8
def create_backup(src, dest_dir):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    src_path = Path(src)
    dest_path = Path(dest_dir) / timestamp
    if src_path.is_file():
        dest_path.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dest_path / src_path.name)
    else: shutil.copytree(src, dest_path)

# %% ../nbs/00_core.ipynb 14
def clean_dates(dates, now=None, max_ages=(2, 14, 60)):
    now = now or datetime.now()
    clean = []
    dates.sort()
    
    for max_age in max_ages:
        lt_max = [d for d in dates if (now - datetime.strptime(d, '%Y%m%d_%H%M%S')).days < max_age]
        if lt_max: clean.append(lt_max[0])

    clean.extend(dates[-5:])  # Keep the newest 5
    return sorted(set(clean))  # Remove duplicates and sort

# %% ../nbs/00_core.ipynb 21
@call_parse
def run_backup(
    src:str, # The source to be backed up
    dest:str, # The destination directory
    max_ages:str="2,14,60", # The max age(s) in days for the different backups
    log_file:str='backup.log'
):
    "Run backup and cleanup old files"
    
    # Set up logging
    logging.basicConfig(filename=log_file, level=logging.DEBUG,
                        format='%(asctime)s - %(levelname)s - %(message)s')
    try:
        create_backup(src, dest)
        logging.info(f"Backup created: {src} -> {dest}")
        max_ages = [int(age.strip()) for age in max_ages.split(',')]
        backups = [d.name for d in Path(dest).iterdir() if d.is_dir()]
        to_keep = clean_dates(backups, max_ages=max_ages)
        for backup in backups:
            if backup not in to_keep:
                shutil.rmtree(Path(dest) / backup)
                logging.info(f"Removed old backup: {backup}")
    except Exception as e:
        logging.error(f"Backup failed: {str(e)}", exc_info=True)
