
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-15T19:18:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a698835f1ff75beccd4697f97a8c471cb12327b3",
 "version": "1.8.76"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
