# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend

    The version of the OpenAPI document: api/v3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jay_sdk_test.api.user_identities_api import UserIdentitiesApi


class TestUserIdentitiesApi(unittest.TestCase):
    """UserIdentitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserIdentitiesApi()

    def tearDown(self) -> None:
        pass

    def test_user_identities_controller_find_one(self) -> None:
        """Test case for user_identities_controller_find_one

        It returns the user identity profile of the first user matching the query
        """
        pass

    def test_user_identities_controller_is_valid_email(self) -> None:
        """Test case for user_identities_controller_is_valid_email

        It returns true if the emailed passed in is linked to any registered users
        """
        pass


if __name__ == '__main__':
    unittest.main()
