# Autogenerated by devscripts/update-version.py

__version__ = '2024.11.11.232805'

RELEASE_GIT_HEAD = 'a9f85670d03ab993dc589f21a9ffffcad61392d5'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.11.11.232805dev'
