MAX_FILE_SIZE = 10 * 1024 * 1024

MARKOV_AI_BASE_URL = "https://www.markovai.xyz"
MARKOV_AI_LOCAL_UPLOAD_ENDPOINT = "/local-upload"
MARKOV_AI_PARSE_ENDPOINT = "/parse"
MARKOV_AI_STREAM_ENDPOINT = "/stream"
MARKOV_AI_STREAM_ASYNC_ENDPOINT = "/stream-async"
MARKOV_AI_STREAM_STATUS_ENDPOINT = "/status"
MARKOV_AI_UPLOAD_ENDPOINT = "/load"
