
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-11-13T05:22:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "72ddc47f36e22b73ebb9a209e69a29629223f2a3",
 "version": "1.30.0.post0.dev123"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
